# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c9c358b5326115fc4bb8f1be393f4f2945cd6112e3b41e138eab0a3034071685e45dcfcac8aba77778a92721fed2423f96cd207a74957b2dea1c0872bf43046

test:
  secret_key_base: 11df8d7b944dde5f3ef7044e661ed0c16c8a4a0bf232569bc7b9b3d7a593e61ecee869b9fe804f4819567a5ebedc61baaed296b50227da819573be75a1683bbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
